[python]
dirs = []
files = ["main.py", "requirements.txt"]

[terraform]
dirs = ["environment"]
files = ["main.tf", "variables.tf", "outputs.tf", "providers.tf", "versions.tf", "environment/dev.tfvars"]
